### ISSUE TITLE
Compatibility with telnet client of Mac OS X

### ISSUE THREAD

**Issue by floatinghotpot** [seanmiddleditch/libtelnet#25]
- Using telnet client of libtelnet, when I send 2 UTF8 Chinese word "火锅", it send "<0xE7><0x81><0xAB><0xE9><0x94><0x85>", which can be correctly printed as "火锅".
- Using telnet of Mac to connect to telnet-proxy, when I type the same word, it sends "<0x67><0x01><0x2B><0x69><0x05>", which cannot be printed correctly.

Why? Is there any encoding in telnet of Mac, which is not handled by libtelnet?

Note: I use telnet-proxy to inspect the network traffic.

**Comment by seanmiddleditch** [comment]
Huh, that is actually a good question. I don't think there's anything special we do that would break encodings. telnet-proxy should be passing on any special telnet options, too.

You might have to use something like Wireshark to figure out what else is different between the direct telnet client and the Mac client. I'd assume it's something in the early connection option negotiation.

It's been a rather very long time since I've really dug into telnet in any capacity, but my best guess at this point would that either the ENVIRON/NEW-ENVIRON handling or the TTYPE handling is at fault. It may be an artifact of telnet-proxy normalizing ENVIRON sub negotiations into NEW-ENVIRON, which perhaps OSX's telnet client has a peculiarity with?

**Comment by seanmiddleditch** [comment]
Closing as out-of-date since we have no more information on the issue.
