### ISSUE TITLE
Shouldn't telnet_send() do CR-NUL and CR-LF translations?

### ISSUE THREAD

**Issue by slcasner** [seanmiddleditch/libtelnet#31]
Why is the implementation of EOL translation only in vprintf() and not in telnet_send()?  The escaping of IAC is in both places.  In my local copy I have merged the EOL code from vprintf() into telnet_send().  This matters for my application because libtelnet interfaces at a lower level where upper levels have already done the printf work.

**Comment by seanmiddleditch** [comment]
`telnet_send` operates on bytes, not text.

There are plenty of cases where an application needs to transmit raw bytes and receive those verbatim on the other end, which EOL translation would break. IAC must be escaped because otherwise an app could not transmit byte 0xFF, but this is okay because that's a reversible translation and the receiving end will translate the escaped content back to its original form.

For your use case, you can just use `telnet_printf` to get the text translation by using `telnet_printf("%s", my_text)`. I'd be more than happy to accept a pull request to add something like a `telnet_send_text(ctx, text, size)` function that adds the EOL translation for connections not in BINARY mode and avoiding the overhead of the printf functionality.

**Comment by slcasner** [comment]
OK, but shouldn't the applications that need to transmit raw bytes and have them received verbatim at the other end be using BINARY mode?  That is, rather than adding a new function telnet_send_text(), shouldn't the EOL translation be added into telnet_send() but be under control of BINARY mode?

**Comment by seanmiddleditch** [comment]
Should? Sure. :)

Do they? Not always. And libtelnet needs to work for those misbehaving apps. Note also that we use telnet_send for SB data where the eol rules don't apply anyway.

**Comment by slcasner** [comment]
OK, will do.  Maybe look at where to put NVT translation on the receive side as well.

For my case, I could not just use telnet_printf("%s", my_text) because at the level where I needed to call libtelnet I had strings with pointer and length that might not be null terminated.  While telnet_printf("%.*s", length, pointer) would probably work, I've always been a bit leery of whether the underlying printf implementation would be counting characters versus bytes or might even have a bug is this less-common use case.  And, as you mention, there's the extra overhead.

**Comment by slcasner** [comment]
I did create a pull request a couple of weeks ago...  I don't see any comments or other response there yet.

**Comment by seanmiddleditch** [comment]
@slcasner  - sorry, busy summer on my end, not much free time for hobby projects. I'm skimming the PR now, but may not have time to do a detailed review for a little while longer (_hopefully_ this weekend is free though).

**Comment by slcasner** [comment]
No problem, just wanted to make sure the PR was noticed.
